import { Button } from "@material-ui/core";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { Document, Page, pdfjs } from "react-pdf";
import { useRecoilValue, useSetRecoilState } from "recoil";
import { AuthResponse, driveAuthState } from "../recoil/atom/drive-auth";
import styles from "../styles/Home.module.css";
import { axiosRequest } from "../utils/axios";
import { base64ToArrayBuffer } from "../utils/base64ToArrayBuffer";
import { getAuthUrl } from "../utils/get-auth-url";
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

interface P {
  code?: string;
  // authResponse?: AuthResponse;
}

const Home: NextPage<P> = ({ code }) => {
  const [data, setData] = useState<any>();
  const authResponse = useRecoilValue(driveAuthState);
  const setDriveAuth = useSetRecoilState(driveAuthState);

  useEffect(() => {
    if (code) {
      axiosRequest<AuthResponse>("GET", `api/drive/token`, {
        params: {
          code,
        },
      }).then((authResponse) => setDriveAuth(authResponse));
    }
  }, [code]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>

        <Button
          onClick={async () => {
            if (window == null) return;

            console.log({ authResponse });

            try {
              let res: any = await axiosRequest("GET", `api/drive/files`, {
                params: {
                  ...authResponse,
                },
              });

              setData(base64ToArrayBuffer(res));
            } catch (error) {
              console.log({ error });
            }
          }}
        >
          Get ScanSnap file list
        </Button>
        {
          <Document file={data}>
            {<Page key={`page_${1}`} pageNumber={1} />}
          </Document>
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}>E Book Shelf</span>
        </a>
      </footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const code = context.query?.code as string;

  if (!code) {
    const url = getAuthUrl();
    context.res.setHeader("location", url);
    context.res.statusCode = 302;
    context.res.end();
    return { props: {} };
  }

  return { props: { code } };
};

export default Home;
